name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "ECR Image Tag"
        required: true
        type: string

env:
  AWS_REGION: us-east-2
  ECR_REGISTRY: 607700977843.dkr.ecr.us-east-2.amazonaws.com
  ECR_REPOSITORY: strapi-app-ecs-pg

jobs:
  terraform-deploy:
    name: Deploy with Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Terraform Init (Remote Backend)
        run: terraform init
        env:
          TF_CLOUD_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          IMAGE_URL=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.event.inputs.image_tag }}
          terraform plan -var="image_url=$IMAGE_URL" -var="db_password=${{ secrets.DB_PASSWORD }}"

      - name: Terraform Apply
        run: |
          IMAGE_URL=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.event.inputs.image_tag }}
          terraform apply -auto-approve -var="image_url=$IMAGE_URL" -var="db_password=${{ secrets.DB_PASSWORD }}"